"use client"

import html2canvas from "html2canvas"
import jsPDF from "jspdf"

export interface ExportOptions {
  filename: string
  title: string
  orientation?: "portrait" | "landscape"
}

export async function exportToPDF(elementId: string, options: ExportOptions): Promise<void> {
  const element = document.getElementById(elementId)
  if (!element) {
    console.error("Element not found for PDF export")
    return
  }

  // Add print class temporarily
  element.classList.add("pdf-export-mode")

  try {
    const canvas = await html2canvas(element, {
      scale: 2,
      useCORS: true,
      logging: false,
      backgroundColor: "#ffffff",
    })

    const imgData = canvas.toDataURL("image/png")
    const pdf = new jsPDF({
      orientation: options.orientation || "portrait",
      unit: "mm",
      format: "a4",
    })

    const pdfWidth = pdf.internal.pageSize.getWidth()
    const pdfHeight = pdf.internal.pageSize.getHeight()
    const imgWidth = canvas.width
    const imgHeight = canvas.height
    const ratio = Math.min(pdfWidth / imgWidth, pdfHeight / imgHeight)
    const imgX = (pdfWidth - imgWidth * ratio) / 2
    const imgY = 10

    // Add header
    pdf.setFontSize(10)
    pdf.setTextColor(128, 128, 128)
    pdf.text(`Generated by StrategyHub | ${new Date().toLocaleDateString()}`, pdfWidth / 2, 7, { align: "center" })

    // Add content
    const scaledWidth = imgWidth * ratio * 0.95
    const scaledHeight = imgHeight * ratio * 0.95

    // Handle multi-page if content is too long
    const pageHeight = pdfHeight - 20 // margins
    const contentHeight = scaledHeight

    if (contentHeight <= pageHeight) {
      pdf.addImage(imgData, "PNG", imgX, imgY, scaledWidth, scaledHeight)
    } else {
      // Multi-page handling
      let remainingHeight = contentHeight
      let sourceY = 0
      let currentPage = 0

      while (remainingHeight > 0) {
        if (currentPage > 0) {
          pdf.addPage()
        }

        const sliceHeight = Math.min(pageHeight, remainingHeight)
        pdf.addImage(imgData, "PNG", imgX, imgY, scaledWidth, scaledHeight, undefined, "FAST")

        remainingHeight -= pageHeight
        sourceY += pageHeight
        currentPage++

        // Safety limit
        if (currentPage > 10) break
      }
    }

    // Save the PDF
    pdf.save(`${options.filename}_${new Date().toISOString().split("T")[0]}.pdf`)
  } finally {
    element.classList.remove("pdf-export-mode")
  }
}
