interface PrintFooterProps {
  toolName: string
  disclaimer?: string
}

export function PrintFooter({ toolName, disclaimer }: PrintFooterProps) {
  return (
    <div className="hidden print:block print-footer mt-8 pt-4 border-t border-border text-center">
      <p className="text-xs text-muted-foreground mb-1">
        Generated by {toolName} — Gaurab Labs | Bharatpur, Chitwan, Nepal
      </p>
      {disclaimer && <p className="text-[10px] text-muted-foreground/80 max-w-xl mx-auto">{disclaimer}</p>}
      <p className="text-[10px] text-muted-foreground/60 mt-2">
        Contact: paudelg97@gmail.com | This report is for educational and self-assessment purposes only.
      </p>
    </div>
  )
}
